/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElAvatari: typeof import('element-plus/es')['ElAvatari']
    ElAvatat: typeof import('element-plus/es')['ElAvatat']
    ElAvator: typeof import('element-plus/es')['ElAvator']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElN: typeof import('element-plus/es')['ElN']
    ElRow: typeof import('element-plus/es')['ElRow']
    NavHeader: typeof import('./src/components/Navigation/NavHeader.vue')['default']
    Navigation: typeof import('./src/components/Navigation/index.vue')['default']
    NavItem: typeof import('./src/components/Navigation/NavItem.vue')['default']
    NotFound: typeof import('./src/components/notFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
